version: "3.9"
name: george
services:
  db:
      container_name: ${DATABASE_HOST}
      image: postgres
      env_file: .env
      restart: unless-stopped
      environment:
        POSTGRES_USER: $DATABASE_USER
        POSTGRES_PASSWORD: $DATABASE_PASSWORD
        POSTGRES_DB: $DATABASE_NAME
      ports:
        - $DATABASE_PORT:$DATABASE_PORT
      networks:
        - trpc_network
      volumes:
        - db_pg_volume:/var/lib/postgres


  api:
    container_name: ${PROJECT_NAME}_api
    build: ./
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - trpc_network
    depends_on:
      - db


networks:
  trpc_network:

volumes:
  db_pg_volume: